# Generated by Django 3.1.5 on 2021-01-23 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frozery', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('phoneno', models.IntegerField(max_length=11)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frozery.customer')),
                ('Dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frozery.dishes')),
            ],
        ),
    ]
