# Generated by Django 3.1.5 on 2021-01-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frozery', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phoneno',
            field=models.CharField(max_length=11),
        ),
    ]
