# Generated by Django 3.1.5 on 2021-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frozery', '0006_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
