# Generated by Django 3.1.5 on 2021-01-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frozery', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
