# Generated by Django 3.1.5 on 2021-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frozery', '0009_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
